FROM mcr.microsoft.com/dotnet/sdk:9.0-windowsservercore-ltsc2022 AS build
WORKDIR /app
COPY myapp/ /app
RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:9.0-windowsservercore-ltsc2022
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "myapp.dll"]